### ISSUE TITLE
Binary compatibility issue with Jetty 9.3

### ISSUE THREAD

**Issue by asevans48** [skinny-framework/skinny-micro#36]
I am running into a Jetty Issue building your example with specified dependencies. I've also tried importing Jetty 9.3 as a library dependency. Is there a dependency I should be including to resolve the following error? How can I resolve this?

```
java.lang.NoSuchMethodError: org.eclipse.jetty.server.handler.HandlerWrapper.updateBean(Ljava/lang/Object;Ljava/lang/Object;Z)V
  at org.eclipse.jetty.server.handler.HandlerWrapper.setHandler(HandlerWrapper.java:97)
  at org.eclipse.jetty.servlet.ServletContextHandler.doSetHandler(ServletContextHandler.java:189)
  at org.eclipse.jetty.servlet.ServletContextHandler.relinkHandlers(ServletContextHandler.java:211)
  at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:172)
  at org.eclipse.jetty.webapp.WebAppContext.<init>(WebAppContext.java:266)
  at org.eclipse.jetty.webapp.WebAppContext.<init>(WebAppContext.java:211)
  at skinny.standalone.JettyServer.start(JettyServer.scala:35)
  at skinny.standalone.JettyServer.start$(JettyServer.scala:32)
  at skinny.micro.WebServer$.skinny$micro$WebServer$$super$start(WebServer.scala:31)
  at skinny.micro.WebServer.start(WebServer.scala:26)
  at skinny.micro.WebServer.start$(WebServer.scala:23)
  at skinny.micro.WebServer$.start(WebServer.scala:31)
  ... 37 elided
```

**Comment by seratch** [comment]
Are you using skinny-micro 1.1? If so, you need to upgrade skinny-micro to 1.2.

- skinny-micro 1.1: jetty 9.2 compatible
- skinny-micro 1.2: jetty 9.3 compatible
